### ISSUE TITLE
Error in deps

### ISSUE THREAD

**Issue by jurgenzz** [sunsetkookaburra/dinocord#1]
```
error TS2339: Property 'next' does not exist on type 'Listener'.

► https://deno.land/std@v0.35.0/http/server.ts:201:49

201     const { value, done } = await this.listener.next();
```

Updating (deps.ts) 
`https://deno.land/std@v0.35.0/ws/mod.ts` 
to 
`https://deno.land/std@v0.36.0/ws/mod.ts` 

fixes the issue.

**Comment by sunsetkookaburra** [comment]
@jurgenzz thank you! this should be fixed now in ebe1b4c. this was a side project a little while back so I'm not using it myself right now. Although now that I have some free time I might add some more stuff 😄.
